steps:
  - id: mvn install
    name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["install", '-Dmaven.test.skip=true']

  - id: Docker Build
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/bien-prj/bien-repository/gs-spring-boot", "--build-arg=no-cache" , "--build-arg=JAR_FILE=target/greetings-0.0.1-SNAPSHOT.jar", "."]

  - id: Docker Push
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'gs-spring-boot'
    - '--image'
    - 'us-central1-docker.pkg.dev/bien-prj/bien-repository/gs-spring-boot:latest'
    - '--region'
    - 'us-central1'

  - id: Deploy to Cloud Run
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'gs-spring-boot'
    - '--image'
    - 'us-central1-docker.pkg.dev/bien-prj/bien-repository/gs-spring-boot:latest'
    - '--region'
    - 'us-central1'
images: ["us-central1-docker.pkg.dev/bien-prj/bien-repository/gs-spring-boot"]
