steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["install"]
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/bien-prj/bien-repository/gs-spring-boot", "--build-arg=JAR_FILE=target/greetings-0.0.1-SNAPSHOT.jar", "."]
images: ["us-central1-docker.pkg.dev/bien-prj/bien-repository/gs-spring-boot"]