apiVersion: v1
kind: Template
labels:
  template: maven-spring-template
metadata:
  name: maven-spring-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: "${LABEL}"
      deploymentconfig: "${NAME}"
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${NAME}"
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}-log"
  spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
   storageClassName: glusterfs-storage
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
  spec:
    strategy:
      type: "Rolling"
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from: 
          kind: ImageStreamTag
          name: "${NAME}:latest"
      type: ImageChange
    replicas: 1
    selector:
      app: "${LABEL}"
      deploymentconfig: "${NAME}"
    template:
      metadata:
        labels:
          app: "${LABEL}"
          deploymentconfig: "${NAME}"
      spec:
        volumes:
        - name: "${NAME}-log"
          persistentVolumeClaim:
            claimName: "${NAME}-log"
        containers:
        - image: " "
          name: "${NAME}"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          volumeMounts:
            - mountPath: /logs
              name: "${NAME}-log"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
- name: LABEL
  displayName: App label
  required: true
  value: maven
