apiVersion: apps/v2
kind: Deployment
metadata:
  name: gs-spring-boot
  namespace: default
  labels:
    app: gs-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-spring-boot
  template:
    metadata:
      labels:
        app: gs-spring-boot
    spec:
      containers:
      - name: gs-spring-boot
        image: us-central1-docker.pkg.dev/bien-prj/bien-repository/gs-spring-boot:latest
        ports:
        - name: gs-spring-boot
          containerPort: 8080
