apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gs-spring-boot-hpa
  labels:
    app: gs-spring-boot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gs-spring-boot
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70