apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-spring-boot
  namespace: default
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: gs-spring-boot
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: bien-prj
        resources:
          limits:
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 4096Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
