apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gs-spring-boot-hpa
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: gs-spring-boot
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
